export const educationalJokes = [
  "There are 10 types of people in the world: those who understand binary, and those who don't.",
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "How many programmers does it take to change a light bulb? None, that's a hardware problem.",
  "A SQL query goes into a bar, walks up to two tables and asks: 'Can I join you?'",
  "Why do Java developers wear glasses? Because they don't C#.",
  "I would love to change the world, but they won't give me the source code.",
  "To understand recursion, you must first understand recursion.",
  "A user interface is like a joke. If you have to explain it, it's not that good.",
  "My code works, I don't know why. My code doesn't work, I don't know why.",
  "If at first you don't succeed, call it version 1.0.",
  "I have a joke about UDP, but you might not get it.",
  "I have a joke about TCP, and I will keep repeating it until you get it.",
  "Why did the programmer quit his job? Because he didn't get arrays.",
  "Software and cathedrals are much the same – first we build them, then we pray.",
  "Programming is 10% writing code and 90% understanding why it's not working.",
  "What is the most used language in programming? Profanity.",
  "Real programmers count from 0.",
  "Optimist: The glass is half full. Pessimist: The glass is half empty. Programmer: The glass is twice as large as necessary.",
  "An SEO expert walks into a bar, bars, pub, tavern, public house, Irish pub, drinks, beer, alcohol...",
  "Why programmers like nature? It has so many bugs.",
  "There is no place like 127.0.0.1.",
  "Knock, knock. Who's there? [very long pause] ... Java.",
  "A web developer walks into a restaurant. He immediately leaves in disgust as the restaurant was laid out in tables.",
  "Don't worry if it doesn't work right. If everything did, you'd be out of a job.",
  "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.",
  "Computers are fast; programmers keep it slow.",
  "Measuring programming progress by lines of code is like measuring airplane building progress by weight.",
  "It's a feature, not a bug.",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
  "First, solve the problem. Then, write the code.",
  "Experience is the name everyone gives to their mistakes.",
  "In order to be irreplaceable, one must always be different.",
  "Java is to JavaScript what car is to Carpet.",
  "Ruby is rubbish! PHP is phpantastic! (Just kidding)",
  "I love deadlines. I like the whooshing sound they make as they fly by.",
  "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
  "Why did the database administrator leave his wife? She had one-to-many relationships.",
  "Why do C programmers never die? They are just cast into void.",
  "I told a joke over a REST API. It got no reaction, it was stateless.",
  "Git commit message: \"I don't know what I did, but it works now.\"",
  "Error 404: Joke not found.",
  "Algorithm: Word used by programmers when they don't want to explain what they did.",
  "Hardware is the part of a computer that you can kick.",
  "Software is the part of a computer that makes you kick the hardware.",
  "Why did the developer go broke? Because he used up all his cache.",
  "Why dot net developers don't wear glasses? Because they see sharp.",
  "How does a computer catch a cold? From a terminal illness.",
  "A byte walks into a bar and orders a pint. Bartender asks 'What's wrong?' Byte says 'Parity error.'",
  "Why did the router break up with the modem? There was no connection.",
  "How do you comfort a JavaScript bug? You console it.",
  "CSS is awesome... until you try to center a div vertically.",
  "What's a programmer's favorite hangout place? Foo Bar.",
  "Why did the constant dump the variable? Because they changed.",
  "Why do python programmers have low self-esteem? Because they are constantly comparing themselves to C.",
  "A loop says to a programmer: 'I'm stuck here, can you break me out?'",
  "React developers are great at handling state. Except their mental state.",
  "Why are assembly programmers always soaking wet? They work below C-level.",
  "What do you call a programmer from Finland? Nerdic.",
  "What did the router say to the doctor? I have a bad connection.",
  "Programmer's spouse: 'Go to the store and buy a loaf of bread. If they have eggs, buy a dozen.' Programmer returns with 12 loaves of bread.",
  "There are two ways to write error-free programs; only the third one works.",
  "One man's crappy software is another man's full-time job.",
  "Linux is only free if your time has no value.",
  "Why do keyboards never sleep? Because they have two shifts.",
  "Why was the computer cold? It left its Windows open.",
  "Database administrators don't play hide and seek because they know where everything is indexed.",
  "A physicist, an engineer and a programmer were in a car driving over a steep alpine pass when the brakes failed. The physicist said: 'We must calculate the friction.' The engineer said: 'We must try to crash-land.' The programmer said: 'Let's push the car back up the hill and see if it happens again.'",
  "The generation of random numbers is too important to be left to chance.",
  "Why was the empty array depressed? It had no elements in its life.",
  "How do you tell HTML from HTML5? Try it out in Internet Explorer. Did it work? No? It's HTML5.",
  "UNIX is simple. It just takes a genius to understand its simplicity.",
  "Why did the variable get a lawyer? It was reassigned.",
  "Vim is great! I've been using it for 2 years... mostly because I don't know how to exit.",
  "I started learning Python today... it has been a deeply slithering experience.",
  "Why did the programmer put his glasses on? To C#.",
  "What is a programmer's favorite glasses brand? C-Sharp.",
  "Programming is like sex. One mistake and you have to support it for the rest of your life.",
  "Computers make very fast, very accurate mistakes.",
  "The best way to get accurate information on Usenet is to post something wrong and wait for corrections.",
  "I'd like to make the world a better place, but they won't give me the source code.",
  "Why did the programmer die in the shower? The shampoo bottle instructions said: 'Lather. Rinse. Repeat.'",
  "Copy-and-Paste was programmed by programmers for programmers.",
  "To err is human, but to really foul things up you need a computer.",
  "Why do programmers mix up Halloween and Christmas? Because Oct 31 == Dec 25.",
  "We'll fix it in production.",
  "The code is compiling. I'll be back in an hour.",
  "Documentation is like pizza: when it is good, it is very, very good; and when it is bad, it is better than nothing.",
  "Why did the function cross the road? To get to the return statement.",
  "A regular expression walks into a bar. The bartender says, 'We don't serve your type here.' The regex says, '.*'",
  "What does a front-end developer do when they get angry? They start flipping tables.",
  "C++: an octopus made by nailing extra legs onto a dog.",
  "To iterate is human, to recurse divine.",
  "There's no test like production.",
  "I'm not escaping. I'm just putting a backslash before my departure.",
  "Programming: when the idea of spending 10 hours to automate a 10-minute task seems like a good investment.",
  "A good programmer is someone who always looks both ways before crossing a one-way street.",
  "An int, a char and a string walk into a bar and order a drink. The bartender asks, 'So, who is paying?' The string says, 'I am, I'm the longest.'",
  "I don't need to test my code, I know it works... *system immediately crashes*",
  "What is the difference between an introverted programmer and an extroverted programmer? An introverted programmer looks at his shoes when he talks to you. An extroverted programmer looks at YOUR shoes when he talks to you.",
  "How to generate a random string? Put a junior dev in front of Vim and tell them to save and exit."
];
